GET http://localhost:5254/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkOTczZDFlMy1jNTFjLTRkYzAtYTU3OC0xZmIwMzkyZmM2YTUiLCJnaXZlbl9uYW1lIjoiV2VuZGVsIiwiZmFtaWx5X25hbWUiOiJTYW50b3MiLCJqdGkiOiIwYWYwMDU3NC01MjZmLTQzM2ItOWQ4YS1jNjhiNTNjMjQzYjIiLCJleHAiOjE3NjE5NjAwODYsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.GAJe3SK2fJHqaNS0VgY8Br4aHmO7deTW5iZAXj1MqNI